export const categories = [
  { name: "Action", type: "genre" },
  { name: "Adventure", type: "genre" },
  { name: "Comedy", type: "genre" },
  { name: "Drama", type: "genre" },
  { name: "Ecchi", type: "genre" },
  { name: "Fantasy", type: "genre" },
  { name: "Horror", type: "genre" },
  { name: "Mahou Shoujo", type: "genre" },
  { name: "Mecha", type: "genre" },
  { name: "Music", type: "genre" },
  { name: "Mystery", type: "genre" },
  { name: "Psychological", type: "genre" },
  { name: "Romance", type: "genre" },
  { name: "Sci-Fi", type: "genre" },
  { name: "Slice of Life", type: "genre" },
  { name: "Sports", type: "genre" },
  { name: "Supernatural", type: "genre" },
  { name: "Thriller", type: "genre" },
  { name: "Josei", type: "tag" },
  { name: "Seinen", type: "tag" },
  { name: "Shoujo", type: "tag" },
  { name: "Shounen", type: "tag" },
  { name: "Kids", type: "tag" },
  { name: "Female Harem", type: "tag" },
  { name: "Male Harem", type: "tag" },
  { name: "Isekai", type: "tag" },
  { name: "Super Power", type: "tag" },
  { name: "School", type: "tag" },
  { name: "Yuri", type: "tag" },
  { name: "Boys' Love", type: "tag" },
  { name: "Crime", type: "tag" },
  { name: "Magic", type: "tag" },
  { name: "Parody", type: "tag" },
  { name: "Military", type: "tag" },
  { name: "Martial Arts", type: "tag" },
  { name: "Demons", type: "tag" },
  { name: "Angels", type: "tag" },
  { name: "Vampire", type: "tag" },
  { name: "Villainess", type: "tag" },
  { name: "Elf", type: "tag" },
  { name: "Succubus", type: "tag" },
  { name: "Tomboy", type: "tag" },
  { name: "Food", type: "tag" },
  { name: "Dragons", type: "tag" },
  { name: "Artificial Intelligence", type: "tag" },
  { name: "Maids", type: "tag" },
  { name: "Witch", type: "tag" }
] as { name: string, type: "genre" | "tag" }[];
